name: "Snyk Gradle"
description: "Check your Gradle application for vulnerabilties using Snyk"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Snyk command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Snyk"
  json:
    description: "Output a snyk.json file with results if running the test command"
    default: false
  docker_image:
    description: "Specify a docker image to use for this action, useful if you want to override the default image"
    default: "snyk/snyk:gradle"
runs:
  using: "docker"
  image: "docker://${{ inputs.docker_image }}"
  env:
    FORCE_COLOR: 2
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: gradle
  args:
  - snyk
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
